### ISSUE TITLE
Error: Could not load JSON data! Please try again later...

### ISSUE THREAD

**Issue by mechanomorph** [fnagel/TYPO3-version-chart#1]
The JSON data can not be loaded due to an error in the XMLHttpRequest.

Console Output:
XMLHttpRequest cannot load http://get.typo3.org/json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://typo3versions.felixnagel.com' is therefore not allowed access.

**Comment by fnagel** [comment]
Where does this error occur? On the live website? Or local? Which browser?

**Comment by mechanomorph** [comment]
This happens on the live website. I tested it with both the newest firefox and chrome versions on different PCs and connections.

**Comment by fnagel** [comment]
Switched back to YQL for fetching the json data. Should work for now. 

Please test and give feedback!

**Comment by mechanomorph** [comment]
Tested with newest Chrome and FF on different Pcs, works fine.

**Comment by fnagel** [comment]
Thanks for the feedback! 

Working on a new version working with https://www.causal.ch/?eID=extensions&route=/v2 as base API. This will work with JSONP and there will not need the YQL bridge.
