### ISSUE TITLE
redirect to https, otherwise the charts are not working

### ISSUE THREAD

**Issue by josefglatz** [fnagel/TYPO3-version-chart#6]

**Comment by fnagel** [comment]
Can you post a screenshot what the JS console says in your browser? Works for me with FF and Chrome on Windows...

**Comment by josefglatz** [comment]
You have to clear caches or open it in incognito mode.

The error is:

Access to XMLHttpRequest at 'http://get.typo3.org/json' from origin 'http://typo3versions.felixnagel.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Error: Could not load JSON data! Please try again later...

I use macOS with Chrome latest stable

**Comment by josefglatz** [comment]
![image](https://user-images.githubusercontent.com/2861556/50839192-1a449080-1360-11e9-8de6-620075a65f6b.png)

**Comment by josefglatz** [comment]
Absolutely no problem ;-) W E  A R E  C O M M U N I T Y ¯\_(ツ)_/¯
